#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

/** XH-S3E-AI_V1.0 (Ricky Hunonic Robot): OLED 0.96" I2C + 2 motor N20 qua L298. */

#define POWER_CHARGE_DETECT_PIN GPIO_NUM_21
#define POWER_ADC_UNIT ADC_UNIT_2
#define POWER_ADC_CHANNEL ADC_CHANNEL_3

/** Motor A (chan trai) — L298 IN1/IN2 */
#define MOTOR_LEFT_IN1_GPIO GPIO_NUM_39  // VOL-
#define MOTOR_LEFT_IN2_GPIO GPIO_NUM_40  // VOL+

/** Motor B (chan phai) — L298 IN3/IN4 */
#define MOTOR_RIGHT_IN1_GPIO GPIO_NUM_43  // TXD — CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG
#define MOTOR_RIGHT_IN2_GPIO GPIO_NUM_44  // RXD

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_SCK GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_DIN GPIO_NUM_6
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_16

#define DISPLAY_SDA_PIN GPIO_NUM_41
#define DISPLAY_SCL_PIN GPIO_NUM_42
#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 64
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true

#define BOOT_BUTTON_GPIO GPIO_NUM_0

#define HUNONIC_SPEED_MIN_EFFECTIVE 30
#define HUNONIC_SPEED_DEFAULT 92
#define HUNONIC_STEP_MS_DEFAULT 500
#define HUNONIC_GAP_MS_DEFAULT 20
#define HUNONIC_STEPS_DEFAULT 2
#define HUNONIC_DURATION_MS_DEFAULT 800
#define HUNONIC_WEB_CONTROL_PORT 8080

#define RICKY_HUNONIC_ROBOT_VERSION "1.0.0"

#endif  // _BOARD_CONFIG_H_
