#include "r839_ir_symbols.h"

/* Auto-generated by tools/generate_r839_ir_symbols.py — do not edit manually. */
/* Export log levels are TX-ready (robot_839_ir inverts on export). */

static const rmt_symbol_word_t r839_ir_sym_forward[] = {
    { .level0 = 1, .duration0 = 4074, .level1 = 0, .duration1 = 1585 },
    { .level0 = 1, .duration0 = 2584, .level1 = 0, .duration1 = 1560 },
    { .level0 = 1, .duration0 = 2584, .level1 = 0, .duration1 = 1560 },
    { .level0 = 1, .duration0 = 2583, .level1 = 0, .duration1 = 1560 },
    { .level0 = 1, .duration0 = 1537, .level1 = 0, .duration1 = 1584 },
    { .level0 = 1, .duration0 = 2583, .level1 = 0, .duration1 = 1561 },
    { .level0 = 1, .duration0 = 2583, .level1 = 0, .duration1 = 1561 },
    { .level0 = 1, .duration0 = 2583, .level1 = 0, .duration1 = 1560 },
    { .level0 = 1, .duration0 = 1538, .level1 = 0, .duration1 = 1583 },
    { .level0 = 1, .duration0 = 1555, .level1 = 0, .duration1 = 1566 },
    { .level0 = 1, .duration0 = 1571, .level1 = 0, .duration1 = 1550 },
    { .level0 = 1, .duration0 = 1585, .level1 = 0, .duration1 = 1562 },
    { .level0 = 1, .duration0 = 2581, .level1 = 0, .duration1 = 1537 },
    { .level0 = 1, .duration0 = 1585, .level1 = 0, .duration1 = 1563 },
    { .level0 = 1, .duration0 = 1559, .level1 = 0, .duration1 = 1561 },
    { .level0 = 1, .duration0 = 1539, .level1 = 0, .duration1 = 1582 },
    { .level0 = 1, .duration0 = 2584, .level1 = 0, .duration1 = 0 },
};

static const rmt_symbol_word_t r839_ir_sym_backward[] = {
    { .level0 = 1, .duration0 = 4125, .level1 = 0, .duration1 = 1561 },
    { .level0 = 1, .duration0 = 2608, .level1 = 0, .duration1 = 1536 },
    { .level0 = 1, .duration0 = 2581, .level1 = 0, .duration1 = 1562 },
    { .level0 = 1, .duration0 = 2580, .level1 = 0, .duration1 = 1537 },
    { .level0 = 1, .duration0 = 1585, .level1 = 0, .duration1 = 1562 },
    { .level0 = 1, .duration0 = 2581, .level1 = 0, .duration1 = 1563 },
    { .level0 = 1, .duration0 = 2581, .level1 = 0, .duration1 = 1562 },
    { .level0 = 1, .duration0 = 1558, .level1 = 0, .duration1 = 1562 },
    { .level0 = 1, .duration0 = 1559, .level1 = 0, .duration1 = 1561 },
    { .level0 = 1, .duration0 = 1549, .level1 = 0, .duration1 = 1572 },
    { .level0 = 1, .duration0 = 1553, .level1 = 0, .duration1 = 1567 },
    { .level0 = 1, .duration0 = 1579, .level1 = 0, .duration1 = 1543 },
    { .level0 = 1, .duration0 = 2592, .level1 = 0, .duration1 = 1552 },
    { .level0 = 1, .duration0 = 1583, .level1 = 0, .duration1 = 1563 },
    { .level0 = 1, .duration0 = 1558, .level1 = 0, .duration1 = 1563 },
    { .level0 = 1, .duration0 = 2581, .level1 = 0, .duration1 = 1563 },
    { .level0 = 1, .duration0 = 2579, .level1 = 0, .duration1 = 0 },
};

static const rmt_symbol_word_t r839_ir_sym_turn_left[] = {
    { .level0 = 1, .duration0 = 4121, .level1 = 0, .duration1 = 1539 },
    { .level0 = 1, .duration0 = 2600, .level1 = 0, .duration1 = 1545 },
    { .level0 = 1, .duration0 = 2595, .level1 = 0, .duration1 = 1550 },
    { .level0 = 1, .duration0 = 2568, .level1 = 0, .duration1 = 1577 },
    { .level0 = 1, .duration0 = 2579, .level1 = 0, .duration1 = 1566 },
    { .level0 = 1, .duration0 = 1574, .level1 = 0, .duration1 = 1548 },
    { .level0 = 1, .duration0 = 1587, .level1 = 0, .duration1 = 1561 },
    { .level0 = 1, .duration0 = 2583, .level1 = 0, .duration1 = 1561 },
    { .level0 = 1, .duration0 = 1560, .level1 = 0, .duration1 = 1562 },
    { .level0 = 1, .duration0 = 1559, .level1 = 0, .duration1 = 1562 },
    { .level0 = 1, .duration0 = 1534, .level1 = 0, .duration1 = 1588 },
    { .level0 = 1, .duration0 = 1581, .level1 = 0, .duration1 = 1540 },
    { .level0 = 1, .duration0 = 1574, .level1 = 0, .duration1 = 1547 },
    { .level0 = 1, .duration0 = 2592, .level1 = 0, .duration1 = 1553 },
    { .level0 = 1, .duration0 = 2543, .level1 = 0, .duration1 = 1602 },
    { .level0 = 1, .duration0 = 1581, .level1 = 0, .duration1 = 1539 },
    { .level0 = 1, .duration0 = 2544, .level1 = 0, .duration1 = 0 },
};

static const rmt_symbol_word_t r839_ir_sym_turn_right[] = {
    { .level0 = 1, .duration0 = 4108, .level1 = 0, .duration1 = 1533 },
    { .level0 = 1, .duration0 = 2577, .level1 = 0, .duration1 = 1568 },
    { .level0 = 1, .duration0 = 2616, .level1 = 0, .duration1 = 1528 },
    { .level0 = 1, .duration0 = 2650, .level1 = 0, .duration1 = 1494 },
    { .level0 = 1, .duration0 = 1564, .level1 = 0, .duration1 = 1555 },
    { .level0 = 1, .duration0 = 2578, .level1 = 0, .duration1 = 1567 },
    { .level0 = 1, .duration0 = 2642, .level1 = 0, .duration1 = 1501 },
    { .level0 = 1, .duration0 = 1597, .level1 = 0, .duration1 = 1523 },
    { .level0 = 1, .duration0 = 2590, .level1 = 0, .duration1 = 1555 },
    { .level0 = 1, .duration0 = 1602, .level1 = 0, .duration1 = 1520 },
    { .level0 = 1, .duration0 = 1653, .level1 = 0, .duration1 = 1494 },
    { .level0 = 1, .duration0 = 1627, .level1 = 0, .duration1 = 1494 },
    { .level0 = 1, .duration0 = 2650, .level1 = 0, .duration1 = 1494 },
    { .level0 = 1, .duration0 = 1627, .level1 = 0, .duration1 = 1494 },
    { .level0 = 1, .duration0 = 1629, .level1 = 0, .duration1 = 1493 },
    { .level0 = 1, .duration0 = 2649, .level1 = 0, .duration1 = 1495 },
    { .level0 = 1, .duration0 = 1625, .level1 = 0, .duration1 = 0 },
};

static const rmt_symbol_word_t r839_ir_sym_stop[] = {
    { .level0 = 1, .duration0 = 4149, .level1 = 0, .duration1 = 1539 },
    { .level0 = 1, .duration0 = 2606, .level1 = 0, .duration1 = 1539 },
    { .level0 = 1, .duration0 = 2601, .level1 = 0, .duration1 = 1517 },
    { .level0 = 1, .duration0 = 2596, .level1 = 0, .duration1 = 1549 },
    { .level0 = 1, .duration0 = 2569, .level1 = 0, .duration1 = 1575 },
    { .level0 = 1, .duration0 = 1608, .level1 = 0, .duration1 = 1539 },
    { .level0 = 1, .duration0 = 2598, .level1 = 0, .duration1 = 1520 },
    { .level0 = 1, .duration0 = 1608, .level1 = 0, .duration1 = 1540 },
    { .level0 = 1, .duration0 = 1582, .level1 = 0, .duration1 = 1539 },
    { .level0 = 1, .duration0 = 1582, .level1 = 0, .duration1 = 1539 },
    { .level0 = 1, .duration0 = 1645, .level1 = 0, .duration1 = 1477 },
    { .level0 = 1, .duration0 = 1544, .level1 = 0, .duration1 = 1577 },
    { .level0 = 1, .duration0 = 1609, .level1 = 0, .duration1 = 1539 },
    { .level0 = 1, .duration0 = 2599, .level1 = 0, .duration1 = 1520 },
    { .level0 = 1, .duration0 = 1609, .level1 = 0, .duration1 = 1539 },
    { .level0 = 1, .duration0 = 2606, .level1 = 0, .duration1 = 1539 },
    { .level0 = 1, .duration0 = 2569, .level1 = 0, .duration1 = 0 },
};

const r839_ir_baked_entry_t kR839IrBakedEntries[] = {
    { "forward", 0x8187D311U, r839_ir_sym_forward, 17 },
    { "backward", 0xBC189E11U, r839_ir_sym_backward, 17 },
    { "turn_left", 0x7263018CU, r839_ir_sym_turn_left, 17 },
    { "turn_right", 0x64CEF564U, r839_ir_sym_turn_right, 17 },
    { "stop", 0xC64BA0ACU, r839_ir_sym_stop, 17 },
};

const size_t kR839IrBakedEntryCount = 5;
