#!/usr/bin/env python3
"""Generate dog_ir_symbols.c from serial EXPORT log or ESP32 NVS partition."""

from __future__ import annotations

import argparse
import glob
import os
import re
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_C = ROOT / "main/boards/ricky-ir-control/dog_ir_symbols.c"
IDF_PATH = os.environ.get("IDF_PATH", "/Users/macbook/esp/v5.5.1/esp-idf")
NVS_TOOL = Path(IDF_PATH) / "components/nvs_flash/nvs_partition_tool/nvs_tool.py"

COMMANDS = [
    "forward",
    "back",
    "left",
    "right",
    "hello",
    "tease",
    "creep",
    "coquetry",
    "pushup",
    "lie_down",
    "sit",
    "stop",
]

EXPORT_HDR_RE = re.compile(
    r"=== EXPORT dog_ir cmd_-?\d+ \w+ fp=0x([0-9A-Fa-f]+) \(\d+ sym\) ==="
)
SYM_RE = re.compile(
    r"\{\s*\.level0\s*=\s*(\d+)\s*,\s*\.duration0\s*=\s*(\d+)\s*,"
    r"\s*\.level1\s*=\s*(\d+)\s*,\s*\.duration1\s*=\s*(\d+)\s*\}"
)


def parse_export_log_ordered(text: str) -> list[tuple[int, list[tuple[int, int, int, int]]]]:
    """Return [(fingerprint, symbols), ...] in log order (first HOC MOI .. #12)."""
    results: list[tuple[int, list[tuple[int, int, int, int]]]] = []
    for match in EXPORT_HDR_RE.finditer(text):
        fp = int(match.group(1), 16)
        body_start = match.end()
        next_hdr = EXPORT_HDR_RE.search(text, body_start)
        body_end = next_hdr.start() if next_hdr else len(text)
        body = text[body_start:body_end]
        syms = [tuple(map(int, m.groups())) for m in SYM_RE.finditer(body)]
        if syms:
            results.append((fp, syms))
    return results


def parse_export_log(text: str) -> dict[str, list[tuple[int, int, int, int]]]:
    ordered = parse_export_log_ordered(text)
    if len(ordered) < len(COMMANDS):
        return {}
    entries: dict[str, list[tuple[int, int, int, int]]] = {}
    for idx, name in enumerate(COMMANDS):
        _fp, syms = ordered[idx]
        entries[name] = syms
    return entries


def decode_blob(blob: bytes) -> tuple[int, list[tuple[int, int, int, int]]] | None:
    if len(blob) < 8:
        return None
    fingerprint, symbol_count = struct.unpack_from("<IB", blob, 0)
    if symbol_count == 0 or symbol_count > 64:
        return None
    offset = 8
    need = offset + symbol_count * 4
    if len(blob) < need:
        return None
    syms = []
    for i in range(symbol_count):
        word = struct.unpack_from("<I", blob, offset + i * 4)[0]
        level0 = word & 1
        duration0 = (word >> 1) & 0x7FFF
        level1 = (word >> 16) & 1
        duration1 = (word >> 17) & 0x7FFF
        syms.append((level0, duration0, level1, duration1))
    return fingerprint, syms


def read_nvs_blobs(nvs_bin: bytes) -> dict[str, list[tuple[int, int, int, int]]]:
    entries: dict[str, list[tuple[int, int, int, int]]] = {}
    for name in COMMANDS:
        key = f"cmd_{COMMANDS.index(name):02d}".encode()
        marker = b"dog_ir\x00" + key + b"\x00"
        # fallback: search fingerprint in blob payloads
        needle = struct.pack("<I", fp)
        pos = 0
        while True:
            pos = nvs_bin.find(needle, pos)
            if pos < 0:
                break
            for size in range(8 + 4, 8 + 64 * 4 + 4):
                chunk = nvs_bin[pos:pos + size]
                decoded = decode_blob(chunk)
                if decoded and decoded[0] == fp:
                    entries[name] = decoded[1]
                    break
            pos += 1
    return entries


def read_nvs_from_port(port: str) -> bytes:
    with tempfile.NamedTemporaryFile(suffix=".bin", delete=False) as tmp:
        tmp_path = tmp.name
    try:
        subprocess.run(
            [
                sys.executable,
                "-m",
                "esptool",
                "--chip",
                "esp32s3",
                "-p",
                port,
                "read_flash",
                "0x9000",
                "0x6000",
                tmp_path,
            ],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            text=True,
        )
        return Path(tmp_path).read_bytes()
    finally:
        Path(tmp_path).unlink(missing_ok=True)


def emit_c(entries: dict[str, list[tuple[int, int, int, int]]], fps: dict[str, int] | None = None) -> str:
    lines = [
        '#include "dog_ir_symbols.h"',
        "",
        "/* Auto-generated by tools/generate_dog_ir_symbols.py — do not edit manually. */",
        "",
    ]
    baked = []
    for name in COMMANDS:
        syms = entries.get(name)
        if not syms:
            raise SystemExit(f"Missing symbols for '{name}'")
        fp = (fps or {}).get(name, 0)
        arr = f"dog_ir_sym_{name}"
        lines.append(f"static const rmt_symbol_word_t {arr}[] = {{")
        for level0, duration0, level1, duration1 in syms:
            lines.append(
                f"    {{ .level0 = {level0}, .duration0 = {duration0}, "
                f".level1 = {level1}, .duration1 = {duration1} }},"
            )
        lines.append("};")
        lines.append("")
        baked.append(
            f'    {{ "{name}", 0x{fp:08X}U, {arr}, {len(syms)} }},'
        )

    lines.append("const dog_ir_baked_entry_t kDogIrBakedEntries[] = {")
    lines.extend(baked)
    lines.append("};")
    lines.append("")
    lines.append(f"const size_t kDogIrBakedEntryCount = {len(COMMANDS)};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--log", help="idf_monitor log file with EXPORT blocks")
    parser.add_argument("--port", help="serial port to read NVS via esptool")
    parser.add_argument("--nvs-bin", help="pre-dumped NVS partition binary")
    args = parser.parse_args()

    entries: dict[str, list[tuple[int, int, int, int]]] = {}

    fps: dict[str, int] = {}
    if args.log:
        log_text = Path(args.log).read_text(errors="ignore")
        ordered = parse_export_log_ordered(log_text)
        entries.update(parse_export_log(log_text))
        for idx, name in enumerate(COMMANDS):
            if idx < len(ordered):
                fps[name] = ordered[idx][0]

    if args.port:
        entries.update(read_nvs_blobs(read_nvs_from_port(args.port)))

    if args.nvs_bin:
        entries.update(read_nvs_blobs(Path(args.nvs_bin).read_bytes()))

    if not entries:
        ports = glob.glob("/dev/cu.usb*") + glob.glob("/dev/cu.wch*") + glob.glob("/dev/cu.SLAB*")
        for port in ports:
            try:
                entries.update(read_nvs_blobs(read_nvs_from_port(port)))
                if len(entries) >= len(COMMANDS):
                    break
            except subprocess.CalledProcessError:
                continue

    if len(entries) < len(COMMANDS):
        missing = [name for name in COMMANDS if name not in entries]
        print("Missing commands:", ", ".join(missing), file=sys.stderr)
        print(
            "Provide --log with EXPORT blocks, or connect ESP and run test-led learn once.",
            file=sys.stderr,
        )
        sys.exit(1)

    OUT_C.write_text(emit_c(entries, fps))
    print(f"Wrote {OUT_C} ({len(COMMANDS)} commands)")
    for name in COMMANDS:
        print(f"  {name}: fp=0x{fps.get(name, 0):08X} ({len(entries[name])} sym)")


if __name__ == "__main__":
    main()
