#!/usr/bin/env python3
"""Convert the "pika" eye GIFs into 1-bit 128x48 frames for the OLED face.

Two source clips: a calm one used while idle/listening, and a talking one whose
mouth flaps, used while the device is speaking.

Usage:
  python3 tools/generate_pika_eyes.py --preview        # only write PNG/GIF previews
  python3 tools/generate_pika_eyes.py --emit           # write assets/eyes_pika_*.c
"""

import argparse
import os

from PIL import Image, ImageSequence

FACE_W = 128
FACE_H = 48
ROW_BYTES = (FACE_W + 7) // 8

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ASSET_DIR = os.path.join(ROOT, "main", "display", "eye_face", "assets")
PREVIEW_DIR = os.path.join(ROOT, "ricky_rsc", "preview")

GIF_DIR = os.path.join(ROOT, "ricky_rsc", "pika")
GIF_NEUTRAL = os.path.join(GIF_DIR, "neutral.gif")
GIF_TALK = os.path.join(GIF_DIR, "talk.gif")

# Playback rate of the generated clips; sources are resampled onto this timeline
# because their frame durations differ and are not always uniform.
FPS = 8

THRESHOLD = 96


def load_frames(gif):
    """Flatten the GIF, compositing partial frames so nothing goes missing.

    Returns (frames, durations_ms).
    """
    im = Image.open(gif)
    canvas = Image.new("RGBA", im.size, (0, 0, 0, 255))
    frames, durations = [], []
    for frame in ImageSequence.Iterator(im):
        canvas.alpha_composite(frame.convert("RGBA"))
        frames.append(canvas.convert("L"))
        durations.append(frame.info.get("duration") or 60)
    return frames, durations


def resample(frames, durations, fps):
    """Pick the frame showing at each tick of a fixed-rate timeline."""
    total = sum(durations)
    period = 1000.0 / fps
    out, idx, elapsed = [], 0, 0.0
    t = 0.0
    while t < total:
        while idx + 1 < len(frames) and elapsed + durations[idx] <= t:
            elapsed += durations[idx]
            idx += 1
        out.append(frames[idx])
        t += period
    return out


def content_bbox(frames):
    box = None
    for f in frames:
        b = f.point(lambda v: 255 if v > 24 else 0).getbbox()
        if b is None:
            continue
        box = b if box is None else (
            min(box[0], b[0]), min(box[1], b[1]), max(box[2], b[2]), max(box[3], b[3])
        )
    return box


def crop_box(bbox, keep_mouth):
    x0, y0, x1, y1 = bbox
    w = x1 - x0
    if keep_mouth:
        return (x0, y0, x1, y1)
    # Keep aspect ratio 128:48 by trimming the bottom (mouth) instead of squashing.
    h = int(round(w * FACE_H / FACE_W))
    h = min(h, y1 - y0)
    return (x0, y0, x1, y0 + h)


def band_map(v):
    """Map the flat GIF palette to monochrome ink.

    Background stays black, the dark iris and the teal outline both become ink,
    and the specular highlight is punched back out so the eye keeps a glint.
    """
    if v >= 240:
        return 0
    if v >= 8:
        return 255
    return 0


def to_bitmap(frame, box, solid_iris):
    img = frame.crop(box)
    if solid_iris:
        img = img.point(band_map)
        img = img.resize((FACE_W, FACE_H), Image.LANCZOS)
    else:
        img = img.resize((FACE_W, FACE_H), Image.LANCZOS)
        img = img.point(lambda v: 255 if v >= THRESHOLD else 0)
    return img.point(lambda v: 255 if v >= 128 else 0).convert("1")


def pack(img):
    px = img.load()
    out = bytearray()
    for y in range(FACE_H):
        row = bytearray(ROW_BYTES)
        for x in range(FACE_W):
            if px[x, y]:
                row[x >> 3] |= 0x80 >> (x & 7)
        out += row
    return bytes(out)


def emit_c(name, frames, path):
    size = ROW_BYTES * FACE_H
    lines = [
        f"// Auto-generated by tools/generate_pika_eyes.py — {name}",
        "#include <stdint.h>",
        "",
        f"static const uint8_t {name}_frame_data[{len(frames)}][{size}] = {{",
    ]
    for idx, data in enumerate(frames):
        lines.append(f"    // frame {idx}")
        lines.append("    {")
        for off in range(0, size, 16):
            chunk = data[off:off + 16]
            lines.append("        " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append(f"const uint8_t* const {name}_frames[] = {{")
    for idx in range(len(frames)):
        lines.append(f"    {name}_frame_data[{idx}],")
    lines.append("};")
    lines.append(f"const uint8_t {name}_frame_count = {len(frames)};")
    lines.append("")
    with open(path, "w") as fh:
        fh.write("\n".join(lines))


def save_preview(tag, imgs, scale=3):
    os.makedirs(PREVIEW_DIR, exist_ok=True)
    big = [i.convert("L").resize((FACE_W * scale, FACE_H * scale), Image.NEAREST) for i in imgs]
    sheet = Image.new("L", (FACE_W * scale, FACE_H * scale * min(4, len(big))))
    step = max(1, len(big) // 4)
    for idx, i in enumerate(big[::step][:4]):
        sheet.paste(i, (0, idx * FACE_H * scale))
    sheet.save(os.path.join(PREVIEW_DIR, f"pika_{tag}_sheet.png"))
    big[0].save(
        os.path.join(PREVIEW_DIR, f"pika_{tag}.gif"),
        save_all=True,
        append_images=big[1:],
        duration=50,
        loop=0,
    )


def build(gif, fps=FPS, resampled=True, keep_mouth=True, solid_iris=False):
    frames, durations = load_frames(gif)
    box = crop_box(content_bbox(frames), keep_mouth)
    picked = resample(frames, durations, fps) if resampled else frames
    return [to_bitmap(f, box, solid_iris) for f in picked]


def ink_area(img):
    return sum(img.convert("L").point(lambda v: 1 if v else 0).get_flattened_data())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", action="store_true")
    ap.add_argument("--preview", action="store_true")
    ap.add_argument("--fps", type=int, default=FPS)
    args = ap.parse_args()

    neutral = build(GIF_NEUTRAL, args.fps)
    talk = build(GIF_TALK, args.fps)

    if args.preview or not args.emit:
        save_preview("neutral", neutral)
        save_preview("talk", talk)
        print("previews ->", PREVIEW_DIR)

    if args.emit:
        os.makedirs(ASSET_DIR, exist_ok=True)
        emit_c("pika_neutral", [pack(i) for i in neutral],
               os.path.join(ASSET_DIR, "eyes_pika_neutral.c"))
        emit_c("pika_talk", [pack(i) for i in talk],
               os.path.join(ASSET_DIR, "eyes_pika_talk.c"))

        # The closing pose is the frame with the least ink; grab a window around it
        # from the unresampled source so the blink keeps its original snap.
        raw = build(GIF_NEUTRAL, resampled=False)
        ink = [ink_area(f) for f in raw]
        low = min(range(len(ink)), key=lambda i: ink[i])
        blink = raw[max(0, low - 4):low + 4]
        emit_c("pika_blink", [pack(i) for i in blink],
               os.path.join(ASSET_DIR, "eyes_pika_blink.c"))

        print(f"pika_neutral: {len(neutral)}, pika_talk: {len(talk)}, "
              f"pika_blink: {len(blink)} (closed at source frame {low})")


if __name__ == "__main__":
    main()
