#!/usr/bin/env python3
"""Generate r839_ir_symbols.c from robot_839_ir serial EXPORT log."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_C = ROOT / "main/boards/ricky-ir-control/r839_ir_symbols.c"

COMMANDS = [
    "forward",
    "backward",
    "turn_left",
    "turn_right",
    "stop",
    "btn_05",
    "btn_06",
    "btn_07",
    "btn_08",
    "btn_09",
    "btn_10",
    "btn_11",
    "btn_12",
    "btn_13",
    "btn_14",
    "btn_15",
    "btn_16",
    "btn_17",
    "btn_18",
    "btn_19",
]

PHASE1_COMMANDS = COMMANDS[:5]

EXPORT_HDR_RE = re.compile(
    r"=== EXPORT r839_ir cmd_(\d+) (\w+) fp=0x([0-9A-Fa-f]+) \(\d+ sym\) ==="
)
SYM_RE = re.compile(
    r"\{\s*\.level0\s*=\s*(\d+)\s*,\s*\.duration0\s*=\s*(\d+)\s*,"
    r"\s*\.level1\s*=\s*(\d+)\s*,\s*\.duration1\s*=\s*(\d+)\s*\}"
)


def parse_export_log(text: str) -> tuple[
    dict[str, list[tuple[int, int, int, int]]],
    dict[str, int],
]:
    latest: dict[int, tuple[int, str, list[tuple[int, int, int, int]]]] = {}

    for match in EXPORT_HDR_RE.finditer(text):
        cmd_idx = int(match.group(1))
        log_name = match.group(2)
        fp = int(match.group(3), 16)
        body_start = match.end()
        next_hdr = EXPORT_HDR_RE.search(text, body_start)
        body_end = next_hdr.start() if next_hdr else len(text)
        body = text[body_start:body_end]
        syms = [tuple(map(int, m.groups())) for m in SYM_RE.finditer(body)]
        if not syms:
            continue
        if cmd_idx < 0 or cmd_idx >= len(COMMANDS):
            print(f"Warning: skip unknown cmd_{cmd_idx:02d} ({log_name})", file=sys.stderr)
            continue
        if log_name != COMMANDS[cmd_idx]:
            print(
                f"Warning: cmd_{cmd_idx:02d} name mismatch log={log_name} "
                f"expected={COMMANDS[cmd_idx]}",
                file=sys.stderr,
            )
        latest[cmd_idx] = (fp, log_name, syms)

    entries: dict[str, list[tuple[int, int, int, int]]] = {}
    fps: dict[str, int] = {}
    for idx, name in enumerate(COMMANDS):
        if idx not in latest:
            continue
        fp, _log_name, syms = latest[idx]
        entries[name] = syms
        fps[name] = fp
    return entries, fps


def emit_c(
    names: list[str],
    entries: dict[str, list[tuple[int, int, int, int]]],
    fps: dict[str, int],
) -> str:
    lines = [
        '#include "r839_ir_symbols.h"',
        "",
        "/* Auto-generated by tools/generate_839_ir_symbols.py — do not edit manually. */",
        "",
    ]
    baked = []
    for name in names:
        syms = entries.get(name)
        if not syms:
            raise SystemExit(f"Missing symbols for '{name}'")
        fp = fps.get(name, 0)
        arr = f"r839_ir_sym_{name}"
        lines.append(f"static const rmt_symbol_word_t {arr}[] = {{")
        for level0, duration0, level1, duration1 in syms:
            lines.append(
                f"    {{ .level0 = {level0}, .duration0 = {duration0}, "
                f".level1 = {level1}, .duration1 = {duration1} }},"
            )
        lines.append("};")
        lines.append("")
        baked.append(f'    {{ "{name}", 0x{fp:08X}U, {arr}, {len(syms)} }},')

    lines.append("const r839_ir_baked_entry_t kR839IrBakedEntries[] = {")
    lines.extend(baked)
    lines.append("};")
    lines.append("")
    lines.append(f"const size_t kR839IrBakedEntryCount = {len(names)};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--log", required=True, help="r839_learn_export.log from idf.py monitor")
    parser.add_argument("-o", "--output", type=Path, default=OUT_C, help="output .c file path")
    parser.add_argument(
        "--phase1",
        action="store_true",
        help="require only 5 basic commands (forward..stop)",
    )
    parser.add_argument(
        "--all20",
        action="store_true",
        help="require all 20 commands",
    )
    args = parser.parse_args()

    required = PHASE1_COMMANDS if args.phase1 else (COMMANDS if args.all20 else None)

    log_text = Path(args.log).read_text(errors="ignore")
    entries, fps = parse_export_log(log_text)

    if not entries:
        print("No EXPORT blocks found in log.", file=sys.stderr)
        sys.exit(1)

    if required is None:
        names = [name for name in COMMANDS if name in entries]
    else:
        names = list(required)
        missing = [name for name in names if name not in entries]
        if missing:
            print("Missing commands:", ", ".join(missing), file=sys.stderr)
            if args.phase1:
                print(
                    "Learn 5 buttons first: Forward, Backward, Turn left, Turn right, Stop.",
                    file=sys.stderr,
                )
            else:
                print("Learn all 20 buttons on robot_839_ir first.", file=sys.stderr)
            sys.exit(1)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(emit_c(names, entries, fps))
    print(f"Wrote {args.output} ({len(names)} commands)")
    for name in names:
        print(f"  {name}: fp=0x{fps.get(name, 0):08X} ({len(entries[name])} sym)")


if __name__ == "__main__":
    main()
